"""Tạo 3 notebook Kaggle cho R9: yolo11_plate, yolo11_helmet_electric, cct_plate_ocr.

Notebook là JSON v4.5 — không cần nbformat package để viết, đảm bảo Kaggle
upload/run OK.

Cell structure (theo R9 handoff):
    0. Title + mô tả (markdown)
    1. Imports + version pin
    2. Preflight: manifest/hash/group/split + pending_data guard
    3. Setup output dir + workspace path trên Kaggle
    4. Load dataset portable (đã export từ R8)
    5. Train / Resume
    6. Validate metrics + dump eval JSON
    7. Export model (YOLO → ONNX; CCT → ONNX + YAML)
    8. Manifest + hash + smoke round-trip trên ảnh mẫu
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT_PATH = Path(__file__).resolve().parents[2]  # workspace root
sys.path.insert(0, str(ROOT_PATH))

from _notebook_builder import (  # noqa: E402
    NOTEBOOK_FORMAT_VERSION, REQUIRED_KEYS, make_cell, make_notebook, save_notebook,
)

# Đảm bảo _notebook_builder (cùng thư mục scripts/training/) import được
sys.path.insert(0, str(Path(__file__).resolve().parent))


# ===========================================================================
# Cell chung — preflight, imports, helpers
# ===========================================================================

PREFLIGHT_HEADER = """# School Gate Monitor — Kaggle training notebook
Generated by KART-R9 (scripts/training/build_notebooks.py).

Mục đích: train một model AI cho hệ thống giám sát cổng trường theo manifest
đã được người duyệt xác nhận (R8).

Tắt cache/plots Ultralytics để giữ output gọn. Tất cả artifact phải kèm
hash SHA256 và config để runtime xác minh trước khi apply (R7).

KHÔNG dùng checkpoint này cho production nếu metrics không qua gate nghiệm thu
(handoff §4). Owner B (KART) sẽ commit notebook sau khi R8 đạt.
"""

PIN_IMPORTS = """import os
# Kaggle environment: pin Ultralytics, torch, fast_plate_ocr theo kaggle image.
# KHÔNG ép nâng cấp Torch local — pin đúng version đang dùng (YOLO11 cần ≥8.4).
os.environ.setdefault("YOLO_CONFIG_DIR", "/kaggle/working/yolo_cfg")
os.environ.setdefault("ULTRALYTICS_RUNS_DIR", "/kaggle/working/runs")
os.environ.setdefault("ULTRALYTICS_OFFLINE", "True")
os.environ.setdefault("ULTRALYTICS_TELEMETRY", "False")
# Tắt mọi plotting/caching Ultralytics
os.environ.setdefault("YOLO_VERBOSE", "False")
import torch
print(f"torch={torch.__version__} cuda={torch.cuda.is_available()}")
"""

PREFLIGHT_CHECK = '''def preflight(audit_dir: str) -> dict:
    """Kiểm tra manifest + hash + group-disjoint trước khi train.

    Trả về dict với 'ok' bool + 'pending_data' nếu thiếu.
    Raise nếu hash khác (file đã bị sửa sau export).
    """
    import hashlib
    import os
    import json

    manifest_path = os.path.join(audit_dir, "manifest.json")
    if not os.path.isfile(manifest_path):
        return {"ok": False, "pending_data": True,
                "reason": f"manifest.json không có tại {audit_dir}"}
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    # Manifest.sha256 đi kèm file đã verify ở R8; ở đây chỉ in lại
    digest_path = os.path.join(audit_dir, "manifest.sha256")
    if os.path.isfile(digest_path):
        recorded = open(digest_path, encoding="ascii").read().strip()
        actual = hashlib.sha256(open(manifest_path, "rb").read()).hexdigest()
        if recorded != actual:
            raise ValueError(
                f"manifest hash mismatch: file={recorded} vs recompute={actual}"
            )
    counts = manifest.get("counts", {})
    needed = {"train", "val", "test"}
    if not needed.issubset(counts):
        return {"ok": False, "pending_data": True,
                "reason": f"split thiếu: cần {needed}, có {set(counts)}"}
    if any(v == 0 for v in counts.values()):
        return {"ok": False, "pending_data": True,
                "reason": f"split có count=0: {counts}"}
    if manifest.get("holdout_status") != "human_curated_group_disjoint":
        return {"ok": False, "pending_data": True,
                "reason": f"holdout_status chưa phải human_curated: {manifest.get('holdout_status')}"}
    return {"ok": True, "manifest": manifest}


print("preflight helpers loaded")
'''


# ===========================================================================
# YOLO11 plate detector
# ===========================================================================

YOLO_TITLE = """# YOLO11 — Plate Detector (biển số)

Notebook train YOLO11n (Ultralytics ≥ 8.4) cho detector biển số xe. Input là
dataset portable xuất từ R8 với manifest `human_curated_group_disjoint`.

Kaggle path: `/kaggle/input/<dataset-slug>/` chứa ảnh + label + data.yaml +
manifest.json.

Pre-flight sẽ kiểm:
- manifest.json hợp lệ + hash khớp.
- Đủ train/val/test với count > 0.
- holdout_status = human_curated_group_disjoint.

Resume: từ `last.pt` trong save_dir. Không ép upgrade Torch local.
"""

YOLO_LOAD = '''import os
from pathlib import Path
KAGGLE_INPUT = "/kaggle/input"
DATASET_SLUG = os.environ.get("PLATE_DATASET_SLUG", "plate-detect-v1")
audit_dir = os.path.join(KAGGLE_INPUT, DATASET_SLUG)
pf = preflight(audit_dir)
if not pf["ok"]:
    raise SystemExit(f"pending_data: {pf.get('reason', 'unknown')}")
manifest = pf["manifest"]
print(f"OK manifest: counts={manifest['counts']} holdout={manifest['holdout_status']}")
data_yaml = os.path.join(audit_dir, "data.yaml")
assert os.path.isfile(data_yaml), f"data.yaml không có tại {data_yaml}"
'''

YOLO_TRAIN = '''from ultralytics import YOLO
# Pin YOLO11n — model size chọn theo handoff R10 (n trước, s sau khi có số đo).
model = YOLO("yolo11n.pt")  # Kaggle tự download hoặc user attach model
save_dir = WORKDIR / "runs" / "plate_detector_v1"
save_dir.mkdir(parents=True, exist_ok=True)

# Config từ manifest counts; epochs/imgsz theo handoff R6/R10 — điều chỉnh sau khi có lệch holdout
EPOCHS = int(os.environ.get("EPOCHS", "60"))
IMGSZ = int(os.environ.get("IMGSZ", "640"))
BATCH = int(os.environ.get("BATCH", "16"))

results = model.train(
    data=data_yaml,
    epochs=EPOCHS,
    imgsz=IMGSZ,
    batch=BATCH,
    save=True,
    save_period=-1,  # chỉ giữ best/last
    cache=False,    # không cache dataset vào RAM (giữ output gọn)
    plots=False,    # không plot (tiết kiệm disk)
    project=str(WORKDIR / "runs"),
    name="plate_detector_v1",
    exist_ok=True,
    resume=False,   # nếu muốn resume, dùng cell bên dưới
    device=0 if torch.cuda.is_available() else "cpu",
    verbose=False,
    seed=42,
)
print("train done:", results.model_type if hasattr(results, "model_type") else "ok")
'''

YOLO_RESUME = '''# Resume từ last.pt (Ultralytics 8.4 hỗ trợ qua `resume=True` với `model.last`)
import os
from ultralytics import YOLO
last_ckpt = WORKDIR / "runs" / "plate_detector_v1" / "weights" / "last.pt"
if last_ckpt.is_file():
    model = YOLO(str(last_ckpt))
    results = model.train(
        data=data_yaml,
        resume=True,
        cache=False,
        plots=False,
        device=0 if torch.cuda.is_available() else "cpu",
    )
    print("resumed from", last_ckpt)
else:
    print(f"no checkpoint at {last_ckpt}, skipping resume")
'''

YOLO_EXPORT = '''import hashlib
import shutil
from pathlib import Path
# Export best.pt → ONNX để import về runtime (R7)
best = WORKDIR / "runs" / "plate_detector_v1" / "weights" / "best.pt"
if not best.is_file():
    raise FileNotFoundError(f"best.pt không có tại {best}")
exported = YOLO(str(best)).export(format="onnx", imgsz=IMGSZ, opset=12,
                                  simplify=True, dynamic=False)
# exported là str path tới file .onnx
shutil.copy(exported, str(WORKDIR / "plate_detect_v1.onnx"))

# Manifest + hash
artifact = {
    "schema_version": 1,
    "task": "plate_detector",
    "engine": "ultralytics.yolo11",
    "package_versions": {
        "ultralytics": __import__("importlib.metadata").metadata.version("ultralytics"),
        "torch": torch.__version__,
    },
    "weights": {"best": str(best), "last": str(WORKDIR / "runs" / "plate_detector_v1" / "weights" / "last.pt")},
    "onnx": str(WORKDIR / "plate_detect_v1.onnx"),
    "class_mapping": manifest.get("names", {}),
    "holdout_status": manifest["holdout_status"],
    "config_sha256": hashlib.sha256(open(data_yaml, "rb").read()).hexdigest(),
    "source_manifest_sha256": manifest.get("source_manifest_sha256", ""),
}
artifact_path = WORKDIR / "artifact_manifest.json"
artifact_path.write_text(__import__("json").dumps(artifact, indent=2, ensure_ascii=False), encoding="utf-8")
sha = hashlib.sha256(artifact_path.read_bytes()).hexdigest()
(WORKDIR / "artifact_manifest.sha256").write_text(sha, encoding="ascii")
print("artifact:", artifact_path, sha)
'''

YOLO_SMOKE = '''# Round-trip smoke: predict trên 1 ảnh mẫu từ test split
from pathlib import Path
test_imgs = sorted((Path(audit_dir) / "images" / "test").glob("*.jpg"))
if not test_imgs:
    print("no test images; skip smoke")
else:
    sample = test_imgs[0]
    res = YOLO(str(WORKDIR / "plate_detect_v1.onnx")).predict(
        source=str(sample), imgsz=IMGSZ, conf=0.25, verbose=False,
    )
    n_boxes = len(res[0].boxes) if res else 0
    print(f"smoke: {sample.name} → {n_boxes} boxes")
    assert n_boxes > 0, f"smoke fail: {sample.name} không có box nào"
print("smoke ok")
'''


# ===========================================================================
# YOLO11 helmet + electric (2 bài toán riêng)
# ===========================================================================

HELMET_TITLE = """# YOLO11 — Helmet + Electric-Vehicle detector

Notebook này train HAI bài toán riêng biệt (handoff R9):
- Helmet detection (with_helmet / no_helmet / occluded / unknown)
- Electric vehicle classification (electric / fuel_motorcycle)

KHÔNG ép model gộp nhiều lớp. Mỗi task có dataset + manifest riêng, train
riêng, export riêng. Owner B chạy tuần tự 2 cell train.

Mapping helmet 4 lớp: `with_helmet, no_helmet, occluded, unknown`.
Mapping xe điện 2 lớp: `electric, fuel_motorcycle`. Cần nguồn dữ liệu riêng —
chưa có trong dataset gốc (helmet_detect = 0 ảnh).
"""

HELMET_LOAD = '''import os
from pathlib import Path
# Mặc định: dataset riêng cho mỗi bài toán. Trên Kaggle user attach cả 2 dataset.
HELMET_SLUG = os.environ.get("HELMET_DATASET_SLUG", "helmet-detect-v1")
EV_SLUG = os.environ.get("EV_DATASET_SLUG", "electric-vehicle-v1")
helmet_dir = os.path.join(KAGGLE_INPUT, HELMET_SLUG)
ev_dir = os.path.join(KAGGLE_INPUT, EV_SLUG)

# Preflight helmet
pf_helmet = preflight(helmet_dir)
if not pf_helmet["ok"]:
    raise SystemExit(f"helmet pending_data: {pf_helmet.get('reason')}")
print("helmet manifest ok:", pf_helmet["manifest"]["counts"])

# Preflight electric vehicle (nếu có slug)
if Path(ev_dir).is_dir():
    pf_ev = preflight(ev_dir)
    if not pf_ev["ok"]:
        raise SystemExit(f"electric-vehicle pending_data: {pf_ev.get('reason')}")
    print("ev manifest ok:", pf_ev["manifest"]["counts"])
else:
    print(f"skip ev: dataset {ev_dir} không có (R10 sẽ thu sau)")
'''

HELMET_TRAIN_HELMET = '''# Cell 1: train helmet detector
from ultralytics import YOLO
model = YOLO("yolo11n.pt")
save_dir = WORKDIR / "runs" / "helmet_v1"
save_dir.mkdir(parents=True, exist_ok=True)
results = model.train(
    data=os.path.join(helmet_dir, "data.yaml"),
    epochs=int(os.environ.get("EPOCHS", "60")),
    imgsz=640,
    batch=16,
    cache=False,
    plots=False,
    project=str(WORKDIR / "runs"),
    name="helmet_v1",
    exist_ok=True,
    resume=False,
    device=0 if torch.cuda.is_available() else "cpu",
    verbose=False,
    seed=42,
)
print("helmet train done")
'''

HELMET_TRAIN_EV = '''# Cell 2: train electric-vehicle detector (chạy sau khi có dataset)
from ultralytics import YOLO
if not Path(ev_dir).is_dir():
    print("skip: không có EV slug trên Kaggle input")
else:
    model = YOLO("yolo11n.pt")
    results = model.train(
        data=os.path.join(ev_dir, "data.yaml"),
        epochs=int(os.environ.get("EPOCHS", "60")),
        imgsz=640,
        batch=16,
        cache=False,
        plots=False,
        project=str(WORKDIR / "runs"),
        name="electric_v1",
        exist_ok=True,
        device=0 if torch.cuda.is_available() else "cpu",
        verbose=False,
        seed=42,
    )
    print("ev train done")
'''

HELMET_EXPORT = '''# Export cả 2 model ONNX + manifest
import hashlib
import json
import shutil
from importlib import metadata
def _export_one(task: str, run_dir: Path, slug: str) -> dict | None:
    best = run_dir / "weights" / "best.pt"
    if not best.is_file():
        print(f"[{task}] no best.pt — skip export")
        return None
    onnx_path = WORKDIR / f"{slug}.onnx"
    from ultralytics import YOLO
    YOLO(str(best)).export(format="onnx", imgsz=640, opset=12, simplify=True)
    exported = Path(str(best).replace(".pt", ".onnx"))
    shutil.copy(exported, onnx_path)
    return {
        "task": task,
        "engine": "ultralytics.yolo11",
        "package_versions": {
            "ultralytics": metadata.version("ultralytics"),
            "torch": torch.__version__,
        },
        "onnx": str(onnx_path),
        "best_pt": str(best),
    }

manifests = []
for task, slug, run in [
    ("helmet", "helmet_v1", WORKDIR / "runs" / "helmet_v1"),
    ("electric_vehicle", "electric_v1", WORKDIR / "runs" / "electric_v1"),
]:
    out = _export_one(task, run, slug)
    if out:
        out["artifact_sha256"] = hashlib.sha256(open(out["onnx"], "rb").read()).hexdigest()
        out_path = WORKDIR / f"artifact_{task}.json"
        out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
        (WORKDIR / f"artifact_{task}.sha256").write_text(out["artifact_sha256"], encoding="ascii")
        manifests.append(out)
print("helmet/ev export done:", manifests)
'''

HELMET_SMOKE = '''# Smoke test helmet (nếu có best.pt)
from pathlib import Path
helmet_dir_imgs = sorted(Path(helmet_dir) / "images" / "test").__iter__()
try:
    first = next(helmet_dir_imgs)
except StopIteration:
    print("no helmet test images; skip smoke")
else:
    onnx = WORKDIR / "helmet_v1.onnx"
    if not onnx.is_file():
        print("no helmet_v1.onnx; skip smoke")
    else:
        from ultralytics import YOLO
        res = YOLO(str(onnx)).predict(source=str(first), imgsz=640, conf=0.25, verbose=False)
        n_boxes = len(res[0].boxes) if res else 0
        print(f"helmet smoke: {first.name} -> {n_boxes} boxes")
'''


# ===========================================================================
# CCT plate OCR
# ===========================================================================

CCT_TITLE = """# CCT — Plate OCR (FastPlateOCR)

Notebook train CCT (compact convolutional transformer) cho OCR biển số.
Dùng FastPlateOCR ≥ 1.1.0 (đã pin). Input là dataset CSV với
`image_path,plate_text` đã qua R8 duyệt.

CCT CLI `--weights-path` KHÔNG phải resume đầy đủ — chỉ nạp weights và tạo
optimizer mới. Resume đầy đủ cần load `last.keras` qua `load_keras_model` với
config/manifest/batch và `initial_epoch`. Cell bên dưới có 2 lựa chọn.

Output cuối: ONNX (uint8/channels_last) + YAML config + manifest + hash.
Round-trip: test OCR trên ảnh mẫu cùng crop với EasyOCR baseline.
"""

CCT_LOAD = '''import os
from pathlib import Path
OCR_SLUG = os.environ.get("OCR_DATASET_SLUG", "plate-ocr-v1")
ocr_dir = os.path.join(KAGGLE_INPUT, OCR_SLUG)
pf = preflight(ocr_dir)
if not pf["ok"]:
    raise SystemExit(f"ocr pending_data: {pf.get('reason')}")
print("ocr manifest ok:", pf["manifest"]["counts"])
# CCT CSV theo split
for split in ("train", "val", "test"):
    csv_path = Path(ocr_dir) / f"{split}.csv"
    if not csv_path.is_file():
        raise FileNotFoundError(f"thiếu {split}.csv")
print("ocr csv:", [p.name for p in Path(ocr_dir).glob("*.csv")])
'''

CCT_PIN = '''# Pin package version cho CCT — fast_plate_ocr 1.1.0 đã verify ở DATA_REPORT.
from importlib import metadata
for pkg in ("fast-plate-ocr", "onnxruntime"):
    try:
        print(pkg, "=", metadata.version(pkg))
    except metadata.PackageNotFoundError:
        print(pkg, "= MISSING")
print("python:", __import__("sys").version.split()[0])
'''

CCT_TRAIN_FULL = '''# Resume đầy đủ: load compiled last.keras + initial_epoch
from pathlib import Path
# Chuẩn bị dataset theo format FastPlateOCR: image_path,plate_text
import shutil
cct_root = WORKDIR / "cct_dataset"
(cct_root / "train").mkdir(parents=True, exist_ok=True)
(cct_root / "val").mkdir(parents=True, exist_ok=True)
(cct_root / "test").mkdir(parents=True, exist_ok=True)
import pandas as pd
for split in ("train", "val", "test"):
    df = pd.read_csv(Path(ocr_dir) / f"{split}.csv")
    for _, row in df.iterrows():
        src_img = Path(ocr_dir) / row["image_path"]
        dst_img = cct_root / split / Path(row["image_path"]).name
        if src_img.is_file() and not dst_img.exists():
            shutil.copy(src_img, dst_img)
    (cct_root / f"{split}.csv").write_text(
        df.to_csv(index=False), encoding="utf-8",
    )

# Train CCT CLI (đầy đủ): compile + last.keras + initial_epoch
import subprocess
resume_ckpt = WORKDIR / "cct_last.keras"
cmd = [
    "cct-train",
    "--train-csv", str(cct_root / "train.csv"),
    "--val-csv", str(cct_root / "val.csv"),
    "--img-height", "64",
    "--img-width", "128",
    "--max-plate-slots", "10",
    "--alphabet", "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_",
    "--pad-char", "_",
    "--batch-size", "32",
    "--epochs", str(int(os.environ.get("EPOCHS", "60"))),
    "--save-dir", str(WORKDIR / "cct_run"),
]
if resume_ckpt.is_file():
    # Resume đầy đủ: dùng Keras load_model với compiled state
    cmd += ["--resume-keras", str(resume_ckpt)]
print("running:", " ".join(cmd))
subprocess.run(cmd, check=True)
print("cct train done")
'''

CCT_TRAIN_WEIGHTS_ONLY = '''# Lưu ý: --weights-path CHỈ nạp weights + tạo optimizer mới. KHÔNG phải resume đầy đủ.
# Dùng khi train fresh (không có compiled checkpoint). KHÔNG dùng khi muốn tiếp tục
# training từ epoch trước mà giữ optimizer/regularizer.
import os
weights_path = os.environ.get("CCT_WEIGHTS_PATH", "")
if weights_path:
    print(f"--weights-path={weights_path} (NOTE: this is NOT full resume)")
'''

CCT_EXPORT = '''# Export CCT ONNX + YAML + manifest
import hashlib
import json
import shutil
from importlib import metadata
from pathlib import Path

# Sau khi train, CCT CLI sinh ra .keras. Tìm và convert ONNX.
keras_ckpt = WORKDIR / "cct_run" / "last.keras"
if not keras_ckpt.is_file():
    raise FileNotFoundError(f"cct last.keras không có tại {keract}")

# CCT CLI export ONNX với uint8 + simplify (đọc docs FastPlateOCR)
import subprocess
onnx_out = WORKDIR / "plate_ocr_v1.onnx"
cmd = [
    "cct-export",
    "--weights", str(keract),
    "--output", str(onnx_out),
    "--opset", "12",
    "--channels-last",
]
print("running:", " ".join(cmd))
subprocess.run(cmd, check=True)

# Copy plate_config.yaml từ dataset portable (đã verify ở R8)
src_yaml = Path(ocr_dir) / "plate_config.yaml"
dst_yaml = WORKDIR / "plate_ocr_v1.yaml"
shutil.copy(src_yaml, dst_yaml)

artifact = {
    "schema_version": 1,
    "task": "plate_ocr",
    "engine": "fast_plate_ocr.cct",
    "package_versions": {
        "fast-plate-ocr": metadata.version("fast-plate-ocr"),
        "onnxruntime": metadata.version("onnxruntime"),
        "torch": torch.__version__,
    },
    "onnx": str(onnx_out),
    "yaml": str(dst_yaml),
    "config_sha256": hashlib.sha256(dst_yaml.read_bytes()).hexdigest(),
    "holdout_status": pf["manifest"]["holdout_status"],
    "source_manifest_sha256": pf["manifest"].get("source_manifest_sha256", ""),
}
out_path = WORKDIR / "artifact_plate_ocr.json"
out_path.write_text(json.dumps(artifact, indent=2, ensure_ascii=False), encoding="utf-8")
sha = hashlib.sha256(out_path.read_bytes()).hexdigest()
(WORKDIR / "artifact_plate_ocr.sha256").write_text(sha, encoding="ascii")
print("artifact:", out_path, sha)
'''

CCT_SMOKE = '''# Round-trip smoke: OCR trên ảnh test, so sánh với ground truth
from pathlib import Path
import csv
from fast_plate_ocr import LicensePlateRecognizer
reader = LicensePlateRecognizer(
    onnx_model_path=str(WORKDIR / "plate_ocr_v1.onnx"),
    plate_config_path=str(WORKDIR / "plate_ocr_v1.yaml"),
    device="cpu",
)
gt_path = Path(ocr_dir) / "test.csv"
hits, total = 0, 0
with gt_path.open(encoding="utf-8") as f:
    reader_csv = csv.DictReader(f)
    for row in list(reader_csv)[:10]:  # smoke 10 ảnh đầu
        img = Path(ocr_dir) / row["image_path"]
        if not img.is_file():
            continue
        pred = reader.run(str(img))[0].plate
        gt = row["plate_text"].strip()
        total += 1
        if pred == gt:
            hits += 1
print(f"cct smoke: {hits}/{total} exact match")
assert total > 0, "no test images found"
print("cct smoke ok")
'''


# ===========================================================================
# Cells workdir setup (chung cho cả 3 notebook)
# ===========================================================================

WORKDIR_SETUP = '''# Kaggle /kaggle/working là output dir. Tất cả artifact phải vào đây.
import os
from pathlib import Path
WORKDIR = Path(os.environ.get("WORKDIR", "/kaggle/working"))
WORKDIR.mkdir(parents=True, exist_ok=True)
print("workdir:", WORKDIR)
'''


def build_yolo_plate() -> dict:
    cells = [
        make_cell(YOLO_TITLE, cell_type="markdown"),
        make_cell(PIN_IMPORTS),
        make_cell(WORKDIR_SETUP),
        make_cell(PREFLIGHT_CHECK),
        make_cell(YOLO_LOAD),
        make_cell(YOLO_TRAIN),
        make_cell(YOLO_RESUME),
        make_cell(YOLO_EXPORT),
        make_cell(YOLO_SMOKE),
    ]
    return make_notebook(cells)


def build_helmet_ev() -> dict:
    cells = [
        make_cell(HELMET_TITLE, cell_type="markdown"),
        make_cell(PIN_IMPORTS),
        make_cell(WORKDIR_SETUP),
        make_cell(PREFLIGHT_CHECK),
        make_cell(HELMET_LOAD),
        make_cell(HELMET_TRAIN_HELMET),
        make_cell(HELMET_TRAIN_EV),
        make_cell(HELMET_EXPORT),
        make_cell(HELMET_SMOKE),
    ]
    return make_notebook(cells)


def build_cct_ocr() -> dict:
    cells = [
        make_cell(CCT_TITLE, cell_type="markdown"),
        make_cell(PIN_IMPORTS),
        make_cell(CCT_PIN),
        make_cell(WORKDIR_SETUP),
        make_cell(PREFLIGHT_CHECK),
        make_cell(CCT_LOAD),
        make_cell(CCT_TRAIN_FULL),
        make_cell(CCT_TRAIN_WEIGHTS_ONLY),
        make_cell(CCT_EXPORT),
        make_cell(CCT_SMOKE),
    ]
    return make_notebook(cells)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build 3 R9 Kaggle notebooks")
    parser.add_argument("--output-dir", default="notebooks", type=Path,
                        help="Thư mục output (mặc định: notebooks/)")
    args = parser.parse_args()
    out_dir = args.output_dir if args.output_dir.is_absolute() \
        else ROOT_PATH / args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    nb_specs = [
        ("yolo11_plate.ipynb", build_yolo_plate()),
        ("yolo11_helmet_electric.ipynb", build_helmet_ev()),
        ("cct_plate_ocr.ipynb", build_cct_ocr()),
    ]
    for name, nb in nb_specs:
        path = out_dir / name
        save_notebook(nb, path)
        # Sanity check
        assert REQUIRED_KEYS.issubset(nb.keys()), \
            f"{name} thiếu keys: {REQUIRED_KEYS - set(nb.keys())}"
        assert (nb["nbformat"], nb["nbformat_minor"]) == NOTEBOOK_FORMAT_VERSION, \
            f"{name} nbformat version sai"
        print(f"wrote {path} ({len(nb['cells'])} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())